### ISSUE TITLE
Raspberry Pi 3

### ISSUE THREAD

**Issue by mrgadotti** [ifsc-lased/daf-pi#1]
Também é possível utilizar uma Raspberry Pi 3 para rodar esse ambiente de testes? Vi que é configurada a Raspberry Pi zero como usb cdc, poderia ser utilizada a UART de outras versões com um conversor USB/Serial?

**Comment by emersonmello** [comment]
@mrgadotti , a Raspberry Pi 3 não tem porta USB OTG, sendo assim não pode atuar como um "USB device", somente como "USB host".
